# Generated by Django 5.1 on 2024-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0004_alter_hotelcart_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='emailaddress',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='total_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
