# Generated by Django 5.1 on 2024-10-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0005_hotelbooking_address_hotelbooking_contact_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='static/uploadProfile')),
                ('Citizen_front', models.ImageField(blank=True, null=True, upload_to='static/UploadCitizen')),
                ('Citizen_back', models.ImageField(blank=True, null=True, upload_to='static/UploadCitizen')),
                ('accountType', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
