# Generated by Django 5.1 on 2024-11-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0006_userprofile_alter_hotelbooking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='booking_type',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_room',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
