# Generated by Django 5.1 on 2024-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0007_remove_hotelbooking_booking_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
