# Generated by Django 5.1 on 2024-11-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0008_rename_address_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='start_date',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
