# Generated by Django 5.1 on 2024-11-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0009_remove_hotelbooking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='maps',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
