# Generated by Django 5.1 on 2024-11-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0010_hotel_maps_alter_hotelbooking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='maps',
        ),
    ]
