# Generated by Django 5.1 on 2024-11-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0011_remove_hotel_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
