# Generated by Django 5.1 on 2024-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0012_alter_hotelbooking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
