# Generated by Django 5.1 on 2024-11-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0013_alter_hotelbooking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
