# Generated by Django 5.1 on 2024-11-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0014_hotel_hotel_url_hotel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
