# Generated by Django 5.1 on 2024-11-19 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0016_alter_hotel_phone_alter_hotelbooking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publice.amenities'),
        ),
    ]
