# Generated by Django 5.1 on 2024-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0017_remove_hotel_amenities_hotel_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='amenities',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(null=True, to='publice.amenities'),
        ),
    ]
