# Generated by Django 5.1 on 2024-11-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0020_userprofile_frist_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Citizen_back',
            field=models.ImageField(blank=True, default='Unknown', upload_to='static/UploadCitizen'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Citizen_front',
            field=models.ImageField(blank=True, default='Unknown', upload_to='static/UploadCitizen'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
