# Generated by Django 5.1 on 2024-11-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0021_alter_userprofile_citizen_back_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Frist_name',
            new_name='frist_name',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Esewa', 'Esewa')], max_length=200, null=True),
        ),
    ]
