# Generated by Django 5.1 on 2024-11-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0022_rename_frist_name_userprofile_frist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Cash on delivery', 'Cash on delivery')], max_length=200, null=True),
        ),
    ]
