# Generated by Django 5.1 on 2024-11-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0024_alter_hotelbooking_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/uploadProfile'),
        ),
    ]
