# Generated by Django 5.1 on 2024-11-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0027_alter_hotelbooking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='services',
        ),
    ]
