# Generated by Django 5.1 on 2024-12-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publice', '0029_hotel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
